apiVersion: v1
kind: ConfigMap
metadata:
  name: pedidos-veloz-config
  namespace: pedidos-veloz
data:
  NODE_ENV: production
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: pedidos_veloz
  ORDERS_SERVICE_URL: http://orders:3001
  PAYMENTS_SERVICE_URL: http://payments:3002
  INVENTORY_SERVICE_URL: http://inventory:3003
  PAYMENT_APPROVAL_LIMIT: "5000"
