apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  namespace: pedidos-veloz
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: payments
          image: ghcr.io/SEU_USUARIO/pedidos-veloz-payments:1.0.0
          imagePullPolicy: IfNotPresent
          command: ["node", "src/services/payments/server.js"]
          ports:
            - containerPort: 3002
          env:
            - name: PAYMENTS_PORT
              value: "3002"
          envFrom:
            - configMapRef:
                name: pedidos-veloz-config
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: payments
  namespace: pedidos-veloz
spec:
  selector:
    app: payments
  ports:
    - name: http
      port: 3002
      targetPort: 3002
