global:
  scrape_interval: 15s

scrape_configs:
  - job_name: api-gateway
    metrics_path: /metrics
    static_configs:
      - targets: ["api-gateway:3000"]

  - job_name: orders-service
    metrics_path: /metrics
    static_configs:
      - targets: ["orders:3001"]

  - job_name: payments-service
    metrics_path: /metrics
    static_configs:
      - targets: ["payments:3002"]

  - job_name: inventory-service
    metrics_path: /metrics
    static_configs:
      - targets: ["inventory:3003"]
